name: package namban for debian

on:
  release:
    types:
      - created

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    container:
      image: debian:12

    steps:
      - uses: actions/checkout@v3
      - name: Install gh-cli
        run: |
          apt update
          apt install gh

      - name: Run the build script
        run: ./package/debian/build.sh
        env:
          REL_TAGNAME: ${{ github.event.release.tag_name }}

      - name: Upload the package file to the release
        run: |
          gh release upload ${{ github.event.release.tag_name }} ./namban*.deb -R ${{ github.repository }}
        env:
          GH_TOKEN: ${{ github.token }}


